### ISSUE TITLE
Change own password without elevation

### ISSUE THREAD

**Issue by Anton-V-K** [proviq/lusrmgr#3]
**Is your feature request related to a problem? Please describe.**
Ordinary user cannot change own password when running the program without administrative priviledges (without elevation).
Following error is shown:
![image](https://user-images.githubusercontent.com/20116984/163691309-2d82e8f4-e046-4910-a8f1-01aac6a90c0a.png)

**Describe the solution you'd like**
The program should allow changing own password without elevation.

**Describe alternatives you've considered**
Windows allows the user to change own password without elevation.

**Comment by akruhler** [comment]
Thanks for your request! While it is possible to invoke the ChangePassword() function to change one's password instead of setting it, this function unfortunately can't be invoked without administrative rights either, even when used on the currently logged in user. The only benefit of this feature being added would consequently be that it allows to change passwords without potential loss of login credentials, provided you know the old account password of course. But since the user could change the password by himself through logging in, it most probably would be an obsolete feature to add.
